
-- CREATE BANK_ACCOUNT
INSERT INTO bank_account VALUES (1, 0, NOW());

-- CREATE OPERATION
INSERT INTO operation VALUES(1, 100, NOW(), 'DEPOSIT', 1);
INSERT INTO operation VALUES(2, -100, NOW(), 'WITHDRAWAL', 1);
